version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pmeet_user
      - MONGO_INITDB_ROOT_PASSWORD=pmeet_pwd
      - MONGO_INITDB_DATABASE=pmeet
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=pmeet_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pmeet_pwd
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
volumes:
  data: { }
  data-redis: { }

networks:
  default:
    name: mongodb_network

