# workflow의 이름을 정의한다.
name: CI

# workflow가 언제 동작할지 정의한다.
# 이 workflow의 경우 main branch에 push 또는 pull_request 이벤트가 발생할 경우 동작한다.
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Add executable permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle except test
        run: ./gradlew build --exclude-task test

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: |
            build/test-results/test/TEST-*.xml

      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: JaCoCo Report
          path: build/reports/jacoco/test/jacocoTestReport.xml
